# numpy 모듈에 대한 연습

In [1]:
import numpy as np

In [2]:
# numpy array 의 사용
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6]], np.float)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
# array 간의 합
c = a + b
print(c)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [4]:
# 요소곱
d = a * b
print(d)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [5]:
print(type(a))
print(a.shape)
print(a[0], a[1])
print(a[0,1])

<class 'numpy.ndarray'>
(2, 3)
[1 2 3] [4 5 6]
2


In [6]:
# 배열을 만들기 위한 다양한 함수 제공
zero = np.zeros((2,3))
ones = np.ones((2,2))
fulls = np.full((2,2), 7)  # 특정 값으로 채워진 배열
eye = np.eye(2)  # 2 x 2 단위행렬
random = np.random.randint(0, 10, (2,3))  # 무작위 정수

print(zero)
print(ones)
print(fulls)
print(eye)
print(random)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[3 3 4]
 [6 5 0]]


In [8]:
np.linalg.norm(np.array([1,2]))

2.23606797749979

In [10]:
# 벡터의 내적
arr1 = np.array([1,2])
arr2 = np.array([2,3])

# 내적을 계산하는 두 가지 방법
arr_dot1 = np.dot(arr1, arr2)
print(arr_dot1)
arr_dot2 = arr1.dot(arr2)
print(arr_dot2)

8
8


In [13]:
# Transpose
arr1_T = a.T
print(arr1_T)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
# broad casting
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr3_like = np.empty_like(arr3)  # input array와 동일한 shape을 가지며 비어있는 행렬 생성

arr3_plus = np.array([1,2,3])
for i in range(4):
    arr3_like[i, :] = arr3[i,:] + arr3_plus  # 모든 열에 이를 더해주기

print(arr3_like)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [18]:
# 행렬을 임의의 순서로 쌓는 함수 tile
arr3_tile = np.tile(arr3_plus, (4, 1))  # 4 x 1로 만들기
print(arr3_tile)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
# shape이 달라도 브로드케스팅으로 인해 문제없이 수행되게 된다. arr3_plus의 복사본이 쌓인 형태로 간주된다
arr3_end = arr3 + arr3_plus
print(arr3_end)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


### numpy에서의 브로드 캐스팅시 규칙
1. 두 배열이 동일한 rank를 가지고 있지 않다면, 낮은 rank의 1차원 배열이 높은 rank 배열의 shape로 간주합니다.  
2. 특정 차원에서 두 배열이 동일한 크기를 갖거나, 두 배열 중 하나의 크기가 1이라면 그 두 배열은 특정 차원에서 compatible하다고 여겨집니다.  
3. 두 행렬이 모든 차원에서 compatible하다면, 브로드캐스팅이 가능합니다.  
4. 브로드캐스팅이 이뤄지면, 각 배열 shape의 요소별 최소공배수로 이루어진 shape가 두 배열의 shape로 간주합니다.  
5. 차원에 상관없이 크기가 1인 배열과 1보다 큰 배열이 있을 때, 크기가 1인 배열은 자신의 차원 수만큼 복사되어 쌓인 것처럼 간주합니다.

In [22]:
# 벡터의 외적을 계산
v = np.array([1,2,3])  # v의 shape는 (3,)
w = np.array([4,5])    # w의 shape는 (2,)
# 외적을 계산하기 위해, 먼저 v를 shape가 (3,1)인 행벡터로 바꿔야 합니다;
# 그다음 이것을 w에 맞춰 브로드캐스팅한뒤 결과물로 shape가 (3,2)인 행렬을 얻습니다,
# 이 행렬은 v와 w 외적의 결과입니다:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# 벡터를 행렬의 각 행에 더하기
x = np.array([[1,2,3], [4,5,6]])
# x는 shape가 (2, 3)이고 v는 shape가 (3,)이므로 이 둘을 브로드캐스팅하면 shape가 (2, 3)인
# 아래와 같은 행렬이 나옵니다:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# 벡터를 행렬의 각 행에 더하기
# x는 shape가 (2, 3)이고 w는 shape가 (2,)입니다.
# x의 전치행렬은 shape가 (3,2)이며 이는 w와 브로드캐스팅이 가능하고 결과로 shape가 (3,2)인 행렬이 생깁니다;
# 이 행렬을 전치하면 shape가 (2,3)인 행렬이 나오며
# 이는 행렬 x의 각 열에 벡터 w을 더한 결과와 동일합니다.
# 아래의 행렬입니다:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# 다른 방법은 w를 shape가 (2,1)인 열벡터로 변환하는 것입니다;
# 그런 다음 이를 바로 x에 브로드캐스팅해 더하면
# 동일한 결과가 나옵니다.
print( x + np.reshape(w, (2, 1)))

# 행렬의 스칼라배:
# x 의 shape는 (2, 3)입니다. Numpy는 스칼라를 shape가 ()인 배열로 취급합니다;
# 그렇기에 스칼라 값은 (2,3) shape로 브로드캐스트 될 수 있고,
# 아래와 같은 결과를 만들어 냅니다:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
