# numpy 모듈에 대한 연습

In [2]:
import numpy as np

In [3]:
# numpy array 의 사용
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6]], np.float)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# array 간의 합
c = a + b
print(c)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [5]:
# 요소곱
d = a * b
print(d)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [6]:
print(type(a))
print(a.shape)
print(a[0], a[1])
print(a[0,1])

<class 'numpy.ndarray'>
(2, 3)
[1 2 3] [4 5 6]
2


In [7]:
# 배열을 만들기 위한 다양한 함수 제공
zero = np.zeros((2,3))
ones = np.ones((2,2))
fulls = np.full((2,2), 7)  # 특정 값으로 채워진 배열
eye = np.eye(2)  # 2 x 2 단위행렬
random = np.random.randint(0, 10, (2,3))  # 무작위 정수

print(zero)
print(ones)
print(fulls)
print(eye)
print(random)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[8 0 5]
 [7 9 7]]


In [9]:
np.linalg.norm(np.array([1,2]))

2.23606797749979