# numpy 모듈에 대한 연습

In [1]:
import numpy as np

In [7]:
# numpy array 의 사용
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6]], np.float)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
c = a + b
print(c)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [9]:
# 요소곱
d = a * b
print(d)

[[ 1.  4.  9.]
 [16. 25. 36.]]
